apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: palashreplicaset310501
  labels:
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: palashshahnode
        image: palash315/palashnehalbhaishah315
        ports:
        - containerPort: 8080