apiVersion: apps/v1
kind: Deployment
metadata:
  name: updatedimage
  labels:
    app: myupdatedapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: myupdatednode
        image: palash315/great_pare
        ports:
        - containerPort: 8080